hdiv_app:
    resource: "@HDIVAppBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

hdiv:
    resource: "@HDIVSecurityBundle/Resources/config/routing.yml"
    prefix:   /